name: Continuous Integration
on: [push]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Set up Node 12.X
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm install

    - name: Lint with eslint
      run: |
        npm test

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Set up Node 12.X
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm install

    - name: Lint with eslint
      run: |
        npm run lint
